using System;
using System.Collections.Generic;
using System.Text;

namespace Model.Interfaces.Sydney {
    public class SydneyEmployee {
        #region Properties
        public string id { get; set; }
        public string nameId { get; set; }
        public string name { get; set; }
        public string assignedTo { get; set; }
        public object description { get; set; }
        public string createDate { get; set; }
        public string lastUpdated { get; set; }
        public string updatedBy { get; set; }
        public string c_salesforceid { get; set; }
        public string c_ownerid { get; set; }
        public string c_isdeleted { get; set; }
        public string c_currencyisocode { get; set; }
        public DateTime c_createddate { get; set; }
        public string c_createdbyid { get; set; }
        public DateTime c_lastmodifieddate { get; set; }
        public string c_lastmodifiedbyid { get; set; }
        public DateTime c_systemmodstamp { get; set; }
        public object c_lastactivitydate { get; set; }
        public DateTime c_lastvieweddate { get; set; }
        public DateTime c_lastreferenceddate { get; set; }
        public string c_active__c { get; set; }
        public string c_cell_phone__c { get; set; }
        public object c_city__c { get; set; }
        public string c_country__c { get; set; }
        public string c_county__c { get; set; }
        public string c_email__c { get; set; }
        public object c_fax__c { get; set; }
        public string c_firstname__c { get; set; }
        public string c_franchisee__c { get; set; }
        public string c_office_location__c { get; set; }
        public object c_home_city__c { get; set; }
        public object c_home_country__c { get; set; }
        public object c_home_county__c { get; set; }
        public object c_home_state__c { get; set; }
        public string c_others__c { get; set; }
        public string c_phone__c { get; set; }
        public string c_show_county__c { get; set; }
        public string c_state__c { get; set; }
        public string c_user__c { get; set; }
        public object c_street_address__c { get; set; }
        public string c_employee_tech_fee__c { get; set; }
        public object c_ttl_home_address__c { get; set; }
        public string c_agent_role__c { get; set; }
        public object c_ttl_home_city__c { get; set; }
        public object c_ttl_home_country__c { get; set; }
        public string c_agent_start_date__c { get; set; }
        public string c_franchisee_tech_fee__c { get; set; }
        public object c_site_web_address__c { get; set; }
        public object c_home_zip__c { get; set; }
        public object c_re_license__c { get; set; }
        public object c_re_license_state__c { get; set; }
        public string c_employee_full_name__c { get; set; }
        public string c_employee_home_page__c { get; set; }
        public string c_ttl_city__c { get; set; }
        public string c_ttl_country__c { get; set; }
        public string c_ttl_county__c { get; set; }
        public string c_ttl_postal_zip_code__c { get; set; }
        public string c_ttl_state_province__c { get; set; }
        public string c_ttl_address__c { get; set; }
        public object c_ttl_home_county__c { get; set; }
        public object c_ttl_home_postal_zip_code__c { get; set; }
        public object c_site_contact_number__c { get; set; }
        public string c_site_email__c { get; set; }
        public string c_ourteam_sequence__c { get; set; }
        public string c_ic_start_date__c { get; set; }
        public object c_ic_expiration_date__c { get; set; }
        public object c_license_expiration_date__c { get; set; }
        public string c_exclude_from_listings_mailing__c { get; set; }
        public string c_is_primary_listing_user__c { get; set; }
        public string c_user_id__c { get; set; }
        public object c_birthdate__c { get; set; }
        public string c_franchise_county__c { get; set; }
        public string c_franchise_state__c { get; set; }
        public string c_franchisee_id__c { get; set; }
        public string c_api_created__c { get; set; }
        public string c_employee_image_view__c { get; set; }
        public string c_employee_image__c { get; set; }
        public string c_employee_imagetemp__c { get; set; }
        public object c_shirt_size__c { get; set; }
        public string c_url_name__c { get; set; }
        public string c_site_url__c { get; set; }
        public string c_franchise_broker_as_defined_in__c { get; set; }
        public string c_franchisee_corporate_name__c { get; set; }
        public string c_franchisee_governing_statue__c { get; set; }
        public string c_employee_has_image__c { get; set; }
        public string c_website_has_image__c { get; set; }
        public string c_add_all_listings__c { get; set; }
        public string c_apply_custom_setting__c { get; set; }
        public object c_associatedfranchises__c { get; set; }
        public object c_listingsortbyemp__c { get; set; }
        public string c_wordpress_site_shortname__c { get; set; }
        public string c_wordpress_agent_county__c { get; set; }
        public string c_wordpress_agent_city__c { get; set; }
        public string c_wordpress_agent_state__c { get; set; }
        public object c_wordpress_custom_sort__c { get; set; }
        public string c_wordpress_custom_sort_order__c { get; set; }
        public string c_wordpress_agent_status__c { get; set; }
        public string c_wordpress_include_all_listing_data__c { get; set; }
        public object c_wordpress_related_locations__c { get; set; }
        public string c_wordpress_agent_active_status__c { get; set; }
        public object c_wordpress_agent_delete_status__c { get; set; }
        public string c_wordpress_agent_country__c { get; set; }
        public string c_wordpress_franchise_owner__c { get; set; }
        public string c_franchise_owner_email__c { get; set; }
        public object c_wordpress_promoted_slider_setting__c { get; set; }
        public object c_associatedagents__c { get; set; }
        public object c_wp_listings_sortorder__c { get; set; }
        public object c_listingsortby__c { get; set; }
        public string c_employee_18_digit_id__c { get; set; }
        public string c_contact__c { get; set; }
        public object c_facebook_url__c { get; set; }
        public object c_linkedin_url__c { get; set; }
        public object c_twitter_url__c { get; set; }
        public object c_membership_level__c { get; set; }
        public string c_oldAssignedTo { get; set; }
        public string c_lastname { get; set; }
        public string c_company { get; set; }
        public string c_bio { get; set; }
        public string c_licenses { get; set; }
        public string c_affiliations { get; set; }
        public string c_awards { get; set; }
        public object c_services_offered { get; set; }
        public object c_about { get; set; }
        public object c_licensed_in { get; set; }
        public string c_New_Listings_Agent_Goal { get; set; }
        public string c_Sold_Deals_Agent_Goal { get; set; }
        public string c_gross_commission_agent_goal { get; set; }
        public object c_Start_Date { get; set; }
        public string c_ActualListings { get; set; }
        public string c_ActualSoldDeals { get; set; }
        public string c_ActualGrossCommisions { get; set; }
        public object c_youtube { get; set; }
        public object c_letterFromPresident { get; set; }
        public object c_Title { get; set; }
        #endregion (Properties)
    }
}
