using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Model;

namespace BizHub.Areas.Identity {
    public class BizHubIdentityDbContext : IdentityDbContext<BizHubUser, BizHubRole, string> {

        #region Constructor
        public BizHubIdentityDbContext(DbContextOptions<BizHubIdentityDbContext> options) : base(options) {

        }
        protected override void OnModelCreating(ModelBuilder builder) {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
        #endregion (Constructor)
    }


    public partial class BizHubDbContext : DbContext {

        //constructor
        public BizHubDbContext(DbContextOptions<BizHubDbContext> options) : base(options) { }
        protected override void OnModelCreating(ModelBuilder builder) {
            //DbSets and classes generated by reverse-engineering
        }
    }
}
